### ISSUE TITLE
Technical Manual on line publication

### ISSUE THREAD

**Issue by ALewis-GA** [INTERMAGNET/wg-tech-man#1]

**Comment by SimonFlower** [comment]
Thanks for the work to create the online demonstrations of the Technical Manual at GitHub and Read the Docs. I think these look really nice, and I imagine will be much simpler to keep up to date, and also allow us to reference individual TM sections. I guess the main purpose of this issue is to discuss advertising, which is present in Read the Docs but not on GitHub, as otherwise the two editions of the manual look the same to me.

For me, the advertising on Read the Docs is not intrusive (it's a single small box at the bottom of each page). I would be fine with this, provided that:

1. This how the advertising is displayed for everyone - in an unobtrusive way
2. It's clear the Intermagnet is not making any money out of the advertising

Intermagnet is not a rich organisation, in fact it has no funds at all, and survives on the good will of it's members. In terms of communicating who we are, I am comfortable that we have to use a service where advertising is used to pay for what we are receiving - to me that is a clear fit for the type of organisation that we are.

**Comment by alanwpthomson** [comment]
I’m not necessarily against the idea, but each of our institutes will have their own view whether they are able to be associated with publications involving advertising, ‘ethical’ or otherwise. Also, IM has no budget to avoid this issue (e.g. “a small monthly payment”). And Simon's two points are important. 

I’m happy to hear what others think and, particularly, whether anyone has experience of gaining permission from their institute to allow ethical advertising in their online publications.

**Comment by stephanbracke** [comment]
Just a small comment on the differences between the two versions. Beside the advertising, the other difference in the readthedocs version is in the bottom left corner where you can switch versions, download pdf (or html) that is linked with it and directly view it on git hub which is nice for reviewers to find the exact file that needs to be changed. For the rest it is correct that the html page is exactly the same.
